### ISSUE TITLE
Actions in update wizard

### ISSUE THREAD

**Issue by sgrossberndt** [kaystrobach/TYPO3.piwikintegration#10]
For a new user it is not really clear which options in the installation process of Piwik are necessary:

OK: Install/Delete
Update: No need for an action, a message would be better.

I guess the actions patch/configure are there to fix the installation after an update from within Piwik? This should be explained in the message for the update.

**Comment by kaystrobach** [comment]
@sgrossberndt any wish for a new wording if not i will close the issue ...
