### ISSUE TITLE
Automatic Piwik install leads to Exception

### ISSUE THREAD

**Issue by sgrossberndt** [kaystrobach/TYPO3.piwikintegration#16]
When Piwik is not installed yet and you go to the statistics module you get an TYPO3 Exception.

Maybe just a message "Piwik is not installed yet, go to update wizard to install" would be sufficient?

`Uncaught TYPO3 Exception
#1392409507: Invalid form/module token detected. Access Denied! (More information)

UnexpectedValueException thrown in file
/var/www/regionale2010.lan/typo3_src-6.2.5/typo3/mod.php in line 26.`

**Comment by kaystrobach** [comment]
problem is reproducedable now with a clean install, seems to be a redirection problem

**Comment by kaystrobach** [comment]
should work with git master
