### ISSUE TITLE
New sites always have the name 'Customer 0'

### ISSUE THREAD

**Issue by sgrossberndt** [kaystrobach/TYPO3.piwikintegration#21]
Caused by autoincrement on idsite: `'name' => 'Customer '.$id,` returns always 'Customer 0' because it when creating $id is 0 and idsite is not incremented until real insertion

**Comment by kaystrobach** [comment]
id is retrieved from the TS Settings, if you specify a higher number this will be taken into account, feel free to reopen if explanation is not clear enough.
