### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by hannesbochmann** [kaystrobach/TYPO3.piwikintegration#27]
I pulled the current piwikintegration version (4.0.0) from the repository and deleted the complete typo3conf/piwik/piwik folder. After installing the extension I wanted to install piwik through the update script of the extension. But that gives me the following error:
Class Piwik\Plugins\TYPO3Login\Auth contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Piwik\Auth::getLogin, Piwik\Auth::getTokenAuthSecret, Piwik\Auth::setPassword, ...)

It happens during the configure piwik step.

**Comment by kaystrobach** [comment]
please retry the latest master, i added some fixes, thanks to @Chrissitopher

**Comment by hannesbochmann** [comment]
Seems to work.
