### ISSUE TITLE
Check, if the getJsFiles() function is needed

### ISSUE THREAD

**Issue by Chrissitopher** [kaystrobach/TYPO3.piwikintegration#39]
I added the function getJsFiles() and its hook registration a few lines above that function, because without that I got a JavaScript error in the default Login plugin of Piwik.

I now learned that the default Login plugin should be disabled.

But when this plugin is disabled, then there is no JS error on the login page, because there *is no* login page.

=> I think the getJsFiles() function and this one line in the hook registration might be superfluous and could be removed.

**Comment by kaystrobach** [comment]
@Chrissitopher keep it as it is for now, if the normal login works as well, I'm fine.
Normally i do not need this ...

**Comment by Chrissitopher** [comment]
I added this issue, because you wrote that piwikintegration should in fact be disabling the default Login plugin. Then however it doesn't make sense to try make JavaScript work inside this plugin. Given that the default plugin should be disabled, function getJsFiles() and its hook registration might well be superfluous.

**Comment by kaystrobach** [comment]
Ok,  then we should check whether login is disabled or not...
