### ISSUE TITLE
Fatal error: Call to undefined method Piwik\Piwik::getJavascriptCode()

### ISSUE THREAD

**Issue by DavidBruchmann** [kaystrobach/TYPO3.piwikintegration#44]
Shown when switching from Dashboard to Trackingcode:

Fatal error: Call to undefined method Piwik\Piwik::getJavascriptCode() in /.../typo3conf/ext/piwikintegration/Classes/Tracking/Tracking.php on line 134

**Comment by kaystrobach** [comment]
should be fixed now
