### ISSUE TITLE
Error when enabling creation of JS by piwikintegration

### ISSUE THREAD

**Issue by DavidBruchmann** [kaystrobach/TYPO3.piwikintegration#45]
Fatal error: Call to a member function getPiwikJavaScriptCodeForSite() on a non-object in /.../typo3conf/ext/piwikintegration/Classes/Tracking/Tracking.php on line 71

**Comment by kaystrobach** [comment]
you mean the independent mode?, will remove it lateron, ext:piwik is recommend anyway to use that ...

**Comment by DavidBruchmann** [comment]
The piwik code never showed up any results too.,
In the moment I get just shown the page "No data has been recorded yet" and it seems I've still to spend much time on it.
In the database I can see some data but I don't know how they are used,I don't see any IP there (maybe in the blob-fields).

I used the JavaScript.code from the page Verwalten -> Tracking Code and added the code just with page.headerData.

**Comment by kaystrobach** [comment]
there are 2 extensions:
* piwikintegration for the BE integration
* piwik for the FE integration

if you have both installed and setup it should work

both currently only with in the git version as the piwik guys change their code base too often ...

**Comment by DavidBruchmann** [comment]
ok extension piwik I got from the TER, so I will replace it by the git version

**Comment by DavidBruchmann** [comment]
the new version never changes my results, so I never get shown any statistics.

**Comment by kaystrobach** [comment]
* is there JS code inserted in the frontend?
* Is the page available somewhere in the net?
* Have enabled (what it is by default), the ignore logged in users option?

**Comment by DavidBruchmann** [comment]
I checked now the JS code and adjusted the path, now I only get the message shown:
Piwik host is not set correctly
The Files can be found with the path that is in the HTML then.

Concerning your documentation there are contrary statements concerning the piwik_host, once it's said to note it without URL-Scheme, but the example is shown with.
Nevertheless, both options or even only "//www.domain.com/some/path/to/piwik/" are not avoiding the message to show up and blocking the whole dashboard.

**Comment by kaystrobach** [comment]
you refer to https://github.com/kaystrobach/TYPO3.piwikintegration/blob/master/Documentation/Extpiwikintegration/Installation/3WaysToAddTheTrackingcode/Index.rst <https://github.com/kaystrobach/TYPO3.piwikintegration/blob/master/Documentation/Extpiwikintegration/Installation/3WaysToAddTheTrackingcode/Index.rst> ???

**Comment by DavidBruchmann** [comment]
Yes, on http://docs.typo3.org/typo3cms/extensions/piwik/ExtPiwik/Configuration/ConfigurationOptions/Index.html is written 
piwik_host: The host / path to your piwik installation without URL-scheme

On page http://docs.typo3.org/typo3cms/extensions/piwik/ExtPiwik/Configuration/RequiredParameters/Index.html
the configuration example is
http://docs.typo3.org/typo3cms/extensions/piwik/ExtPiwik/Configuration/RequiredParameters/Index.html


The page I don't want to post here and concerning the option to en- or disaple tracking for logged-in users I don't find now but I use another browser for creating visits anyway, just not sure if my IP is then already excluded by usage of the first browser ...
So some basic-infos are missing how it's working in detail, but that might be a piwik-issue and not a fault of your extensions.

**Comment by kaystrobach** [comment]
If you use piwikintegration, there is no need to define the host, read the piwikintegration docs linked above ...

**Comment by DavidBruchmann** [comment]
ok, used the config-editor and see the JS-Code is different, that's all what is included now:


<script type="text/javascript">
	/* <![CDATA[ */
		try {
			var _paq = _paq || [];
			(function() {
				_paq.push(["enableLinkTracking"]);

				_paq.push(["setTrackerUrl", "typo3conf/piwik/piwik/piwik.php"]);
				_paq.push(["setSiteId", "1"]);
				_paq.push(["trackPageView"]);
				var d = document;
				var g = d.createElement("script");
				var s = d.getElementsByTagName("script")[0];
				g.type = "text/javascript";
				g.defer = true;
				g.async = true;
				g.src = "typo3conf/piwik/piwik/piwik.js";
				s.parentNode.insertBefore(g, s);
			})();
		} catch(err) {}

	/* ]]> */
</script>
<noscript><p><img src="typo3conf/piwik/piwik//piwik.php?idsite=1&rec=1&apiv=1&r=216269&cip=114.79.54.148&_id=f206e9dc3c8b79db&_idts=1428496459&_idvc=26&_viewts=1428561255&url=http%3A%2F%2Fwww.domain.com%2Fsome-path%2F&urlref=http%3A%2F%2Fwww.domain.com%2Fanother-path%2F" style="border:0" alt=""/></p></noscript>

**Comment by DavidBruchmann** [comment]
In the browser-console I can see that the files of piwik are loaded, so the paths are correct.
Nevertheless the dashboard keeps empty.
Versions of the extensions are shown as 
piwik	: 3.1.0
piwikintegration: 4.0.0
and I gott them both here from github.

**Comment by kaystrobach** [comment]
piwik calculates the stats on demand or via cron, please check the piwik settings, if there is set, that views should just be calculated on cron events, you won't see any stats ... set it to on demand please

**Comment by kaystrobach** [comment]
if that's the case, i will create a new ticket, which will have the clue to set a usefull default

**Comment by DavidBruchmann** [comment]
yes thanks for the hint and all your time.
Concerning cron I thought already about it as the scheduler is not working in that version.

**Comment by kaystrobach** [comment]
so this was the problem?

**Comment by DavidBruchmann** [comment]
mhm, as you can see on my tickets it's a stony way.
piwik was already used and I made the update for the customer.
Concerning knowledge I just knew piwik from times where it was still a webservice.
So different versions and missing classes are confusing and update never seems being possible. New installation as black box only without looking too deep in details fails if you don't know the basic principles.
As I had already data in the database, collected with different versions of JS-code, I've no clue if the switch was required or if it's changing something on the data or only in the source-HTML / JS.
Will try now the setup the cron and hope that it's running then.
