### ISSUE TITLE
documentation-problem or fault?

### ISSUE THREAD

**Issue by DavidBruchmann** [kaystrobach/TYPO3.piwikintegration#46]
Hi,

having installed the extension I see a dashboard with the hint "No data has been recorded yet" even I logged out and used additionally another browser to call a few pages.
So when the data get populated (without scheduler)?

**Comment by hannesbochmann** [comment]
Have you configured that archiving is done in the browser not via cron? Have you included the necessary JavaScript for the tracking in the FE?

**Comment by DavidBruchmann** [comment]
In general the mode without cronjob should work but piwikintegration never seems to work with it.
I got it working only when I setup piwik without extension and afterwards I install piwikintegration to connect it. I created dummy-tables first then and afterwards I changed the suffix to the real existing tables in the config file.

**Comment by kaystrobach** [comment]
Piwikintegration switched that off in the Settings, but you can reenable it

**Comment by kaystrobach** [comment]
In General it's Bad to calculate that in demand AS this can take quite long. ....

**Comment by DavidBruchmann** [comment]
Some websites with TYPO3 have 200 clicks in a month and for those sites I don't mind.
And often the customers desire piwik but never look at all at it.
Apart from that configuration isn't really intuitive. I made a copy of the site on another domain and replaced piwik because it ignored the new data and I never got the dashboard showing anything but the general hint to add the javascript. I could have done a setup like described above but I had my doubts that updates will work well too.

**Comment by kaystrobach** [comment]
Please check if changing this setting fixes your problem https://github.com/kaystrobach/TYPO3.piwikintegration/blob/master/Classes/Lib/Config.php#L141

Should be 1 IMHo if so i can change that and would create the Scheduler taks automatically and thisnone could switch off this Option again ;)

----- Originale Nachricht -----
Von: DavidBruchmann <notifications@github.com>
Gesendet: 20.10.2015 - 18:12
An: "kaystrobach/TYPO3.piwikintegration" <TYPO3.piwikintegration@noreply.github.com>
Betreff: Re: [TYPO3.piwikintegration] documentation-problem or fault? (#46)

**Comment by DavidBruchmann** [comment]
The dashboard never is changing but the table user_piwikintegration_log_visit is empty too.
I have the JS-Code on the page and logged out, called the page with the same and another browser.
I get a 400 Error concerning piwik.php (Bad Request), is that normal?
Don't know it that is avoiding counting.

**Comment by kaystrobach** [comment]
have you installed adblockers or ghostery? they may block piwik ...

**Comment by DavidBruchmann** [comment]
No, switched Virus Scanner of and safe mode in IE.
In FF I had a look at the request-header, may be a bit strange or wrong because of "Accept image/png":

Host: domain.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:41.0) Gecko/20100101 Firefox/41.0
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://domain.com/path/
Cookie: be_typo_user=7bbbab82fb0d3caec30c7684e6e2afa5; PHPSESSID=slctaodf7oivs8aqc31hcfjul6; PIWIK_SESSID=rtl9vag1b7p3829qhmg3ir1i37; fe_typo_user=8c3d09fdafe9bd475408cc41c135d37f; _pk_id.1.f3f0=b4f28387ea1b5a48.1445430112.1.1445431523.1445430112.; _pk_ses.1.f3f0=*; phpMyAdmin=slctaodf7oivs8aqc31hcfjul6
Connection: keep-alive

**Comment by kaystrobach** [comment]
looks like the no script part of a piwik request ...

**Comment by DavidBruchmann** [comment]
I removed the no-script part, same result.
When I just show the noscript part it's working without error but surly all the parameters are missing.
Seems I had to find out which parameter is causing the error.
But even with the image link, the table is still empty.
