### ISSUE TITLE
Compatibility with Piwik 2.14

### ISSUE THREAD

**Issue by Chrissitopher** [kaystrobach/TYPO3.piwikintegration#50]
The extension needs an update for Piwik 2.14:

* Adjust Login code
 * Exception handling needs update
* Container needs to be created:
 * Uncaught exception 'Piwik\Container\ContainerDoesNotExistException' with message 'The root container has not been created yet.' in typo3conf\piwik\piwik\core\Container\StaticContainer.php:40

**Comment by kaystrobach** [comment]
see current master, worked on it some minutes ago ...

**Comment by Chrissitopher** [comment]
Ahh, great! :-)

I'll push the remaining changes I have here then...

**Comment by kaystrobach** [comment]
atleast in the testing environment it worked.

There were just some token warnings.

I also started to switch to namespaces in this change set and will push that further with a larger refactoring ...

**Comment by Chrissitopher** [comment]
See https://github.com/kaystrobach/TYPO3.piwikintegration/pull/51 and https://github.com/kaystrobach/TYPO3.piwikintegration/pull/52
