### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by hannesbochmann** [kaystrobach/TYPO3.piwikintegration#54]
In piwik/plugins/TYPO3Login/Auth.php is missing \ in front of the Exception class in line 251. Because of Namesspaces the call leads to Class 'Piwik\\Plugins\\TYPO3Login\\Exception' not found.
Adding the \ to Exception is enough.

**Comment by kaystrobach** [comment]
have you checked the git version, or just the TER version? - thanks

**Comment by hannesbochmann** [comment]
The TER Version. But as I see it's in the git version, too.
@see https://github.com/kaystrobach/TYPO3.piwikintegration/blob/master/piwik_patches/plugins/TYPO3Login/Auth.php#L251

**Comment by kaystrobach** [comment]
fixed in git repo, would be glad, if you could check it before release :dancer:

**Comment by hannesbochmann** [comment]
Looks fine to me. Thanks.
