### ISSUE TITLE
usage of token_auth broken

### ISSUE THREAD

**Issue by hannesbochmann** [kaystrobach/TYPO3.piwikintegration#55]
I have created a piwik superuser inside piwik which is no TYPO3 BE user. I need a constant piwik superuser with a constant token_auth so I can run the archiving via the web interface (cron not working).
When I call the archiving like http://www.domain.com/typo3conf/piwik/piwik/misc/cron/archive.php?token_auth=myS3cr3tTok3n it only works when I use the token_auth of my own piwik superuser which is present in TYPO3. With the token_auth of the piwik only superuser it works not. As soon as I replace the TYPO3Login plugin with the normal Login plugin everything works fine.

Sorry had no time so far to dig deeper where the problem exactly is located.

**Comment by kaystrobach** [comment]
easy, piwikintegration replaces the piwik authentication mechanism, so the internal piwik users are simply ignored, just create a piwik web cron user in TYPO3 login once, and open piwikintegration once and it should work

**Comment by hannesbochmann** [comment]
Thanks. The downside is that the user has to be in TYPO3 an admin to be a superuser in piwik. I would like to have a superuser in piwik but no TYPO3 admin. But I think this is not possible in the moment.

**Comment by kaystrobach** [comment]
@hannesbochmann you can define one superuser in the piwikconfiguration file, this one is working IMHO, anyway i'm open for patches if you need that :smile:
