### ISSUE TITLE
Update TCA to prevent TCA migration and to improve performance

### ISSUE THREAD

**Issue by Chrissitopher** [kaystrobach/TYPO3.piwikintegration#61]
Running piwikintegration currently forces a TCA migration for the field be_user.tx_piwikintegration_api_code.

The full message reads:

Automatic TCA migration done during bootstrap. Please adapt TCA accordingly, these migrations will be removed. The backend module "Configuration -> TCA" shows the modified values. Please adapt these areas:

- The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'tx_piwikintegration_api_code' has been migrated, from TCA table "be_users['types']['0']['showitem']"to "be_users['types']['0']['columnsOverrides']['tx_piwikintegration_api_code']['defaultExtras']".
- The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'tx_piwikintegration_api_code' has been migrated, from TCA table "be_users['types']['1']['showitem']"to "be_users['types']['1']['columnsOverrides']['tx_piwikintegration_api_code']['defaultExtras']".

The field definition should be moved to Configuration/TCA and updated.

**Comment by kaystrobach** [comment]
kannst du dir das mal ansehen? - wäre super, ich bin die woche auf der t3uxw und kann es nicht versprechen

**Comment by Chrissitopher** [comment]
The issue is caused by the TCA changes in ext_tables.php and especially by the 
    `'tx_piwikintegration_api_code;;;;1-1-1'`
in the call to `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes()`.

I'll try fixing the whole migration thing.

**Comment by kaystrobach** [comment]
Wenn nicht, gib Bescheid, das ist dchnell gemacht

**Comment by Chrissitopher** [comment]
Ehh, I already pushed the commit... ;-)

https://github.com/Chrissitopher/TYPO3.piwikintegration/commit/279e0c638bef342475cc9694a391fb824fbbc53b

Du musst den nur noch mergen. ;-)

**Comment by kaystrobach** [comment]
Pr bitte 😉

**Comment by Chrissitopher** [comment]
=> #88! 😉
