### ISSUE TITLE
Update usage of TYPO3_db constants

### ISSUE THREAD

**Issue by Chrissitopher** [kaystrobach/TYPO3.piwikintegration#66]
In TYPO3 8.1, the PHP constants `TYPO3_db`, `TYPO3_db_username`, `TYPO3_db_password` and `TYPO3_db_host` which were used when TYPO3 initialized the database connection have been removed.

Instead, use the configuration data within `$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']` to determine the username, password and host information for the default database connection.

Here is an overview:

```
============================   ===============================================
Old name                       New name
============================   ===============================================
DB/username                    DB/Connections/Default/user
DB/password                    DB/Connections/Default/password
DB/host                        DB/Connections/Default/host
DB/port                        DB/Connections/Default/port
DB/socket                      DB/Connections/Default/unix_socket
DB/database                    DB/Connections/Default/dbname
SYS/setDBinit                  DB/Connections/Default/initCommands
SYS/no_pconnect                DB/Connections/Default/persistentConnection
SYS/dbClientCompress           DB/Connections/Default/driverOptions
                               Valid values for MySQLi connections:
                               0  compression disabled
                               32 compression enabled
============================   ===============================================
```

**Comment by kaystrobach** [comment]
And the whole DB layer has been removed and replaced with doctrine

So either we need a new branch for 8.x or switch to the api approach ...

Von meinem iPhone gesendet

**Comment by Chrissitopher** [comment]
After #47, #75 and #76, issue #76 should get merged.

Afterwards, this issue here might already be more or less solved.
