### ISSUE TITLE
PHP Fatal error:  Call to a member function getPluginName() on boolean in .../piwik/core/Theme.php on line 39

### ISSUE THREAD

**Issue by tobada** [kaystrobach/TYPO3.piwikintegration#72]
I'm using the extension piwikintegration 4.3.3 together with piwik 3.1.0. Typo3 Version is 6.2.26.
The Error occurs only on the loginpage of the website, if I pass it (visit the Site while being logged in in backend) the other pages seem to work fine.

Do I have to set the theme somehow?

**Comment by kaystrobach** [comment]
piwik 3.x is not tested, please post the complete stack trace (debug mode in TYPO3 / Piwik) to let me get an idea ;)

**Comment by tobada** [comment]
Sorry, i tried some debug methods but couldnt get the stacktrace. I don't want to play around to much, because its a productive system. Can you elaborate which debug option to use?

Meanwhile i found a dirty hotfix: 
changed
'$this->themeName = $plugin->getPluginName();'
to
'$this->themeName = "default";'
in the line mentioned in this issues name (../piwik/core/Theme.php on line 39)

**Comment by kaystrobach** [comment]
Sounds like the plugin for the theme is not activated
