### ISSUE TITLE
Remove LocalConfiguration.php include from Auth.php

### ISSUE THREAD

**Issue by astehlik** [kaystrobach/TYPO3.piwikintegration#75]
I'm not quite sure what the code block in `piwik_patches/plugins/TYPO3Login/Auth.php` does. It seems to read the TYPO3 database configuration but does not do anything with it.

It defines the `TYPO3DB` constant but I could not find any usage of it.

All the queries in the Auth class are done with `\Piwik\Db`.

I would not care if I didn't have quite some problems with this code because I'm using symlinks in my installation (Surf deployment, Piwik is inside the shared folder). With this kind of setup, the path to the LocalConfiguration.php is always wrong beacuse PHP resolves the real path of the symlink.

I removed the snippet and everything still seems to work.

Can this block be removed? If not, could you explain its purpose?

Thank you!

**Comment by kaystrobach** [comment]
@astehlik do you mean the code block before the class definition? If so i think it's a leftover from the last refactoring 😄  I happily accept a PR for that.
