### ISSUE TITLE
Worlmap does not show any data

### ISSUE THREAD

**Issue by astehlik** [kaystrobach/TYPO3.piwikintegration#77]
This is a really strange problem. Everything is working fine in the Backend except the visitors map.

The error occurs, when Piwik makes an AJAX request to:

`http://myurl.com/typo3conf/piwik/piwik/index.php?period=range&idSite=1&segment=&date=last30&format=json&showRawMetrics=1&module=API&method=Live.getLastVisitsDetails&filter_limit=100&showColumns=latitude%2Clongitude%2Cactions%2ClastActionTimestamp%2CvisitLocalTime%2Ccity%2Ccountry%2CreferrerType%2CreferrerName%2CreferrerTypeName%2CbrowserIcon%2CoperatingSystemIcon%2CcountryFlag%2CidVisit%2CactionDetails%2CcontinentCode%2Cactions%2Csearches%2CgoalConversions%2CvisitorId%2CuserId&minTimestamp=-1`

```json
{"result":"error","message":"You can't access this resource as it requires an 'view' access for the website id = 1."}
```
When I call this URL directly it works fine. The problem seems to be that an empty token is
submitted in the form data:

```
token_auth:null
```
Piwik Version is 3.0.4

piwikintegration version is 4.4.0

This seems to be a problem with the TYPO3Login plugin. When I disable it, the correct token is submitted in the AJAX requests.

Maybe you can give me a hint where to look. I'll try to provide a pull request.

**Comment by kaystrobach** [comment]
Still a problem?
