### ISSUE TITLE
Make file integrity check green again

### ISSUE THREAD

**Issue by Chrissitopher** [kaystrobach/TYPO3.piwikintegration#82]
File integrity check in Piwik 3 complains about the file `piwikintegration.php` in the Piwik root folder.

Piwik would [accept the code](https://github.com/matomo-org/matomo/blob/3.x-dev/config/global.php#L82), if it was inside `config/*.config.ini.php` or in `bootstrap.php`. 

`bootstrap.php` might be the better choice as we are not providing Piwik configuration in that file. A simple 

`
define('PIWIK_PATCH_VERSION', $EM_CONF['piwikintegration']['version']);
`

should do. Needs a fix at the two places in `Classes/Lib/Install.php`.

**Comment by kaystrobach** [comment]
Can you add more info here we please?
