### ISSUE TITLE
Class 'tx_piwikintegration_install' not found

### ISSUE THREAD

**Issue by vasyugan** [kaystrobach/TYPO3.piwikintegration#84]
Running typo3 7 LTS on a Nginx server, Ubuntu 16.4, with PHP FPM. After installing piwikintegration and selecting "configure" I see 

Oops, an error occurred!

Class 'tx_piwikintegration_install' not found

The class of course is present, in typo3conf/ext/piwikintegration/Classes/Lib/Install.php 

The log says:

--- 
  | Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class  'tx_piwikintegration_install' not found \| Error thrown in file  /var/www/chrooted/uferwerkweb/htdocs/uferwerk.org/typo3temp/ExtensionManager/UpdateScripts/ext_update4202a2abea4e1159cdd1e4c129d3ab4a.php  in line 64. Requested URL:  https://uferwerk.org/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=6efba724ddcec0056b25a5c09d5a657698582502&tx_extensionmanager_tools_extensionmanagerextensionmanager%5BextensionKey%5D=piwikintegration&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=show&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=UpdateScript
-- | --

  | Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class  'tx_piwikintegration_install' not found \| Error thrown in file  /var/www/chrooted/uferwerkweb/htdocs/uferwerk.org/typo3conf/ext/piwikintegration/Classes/Lib/Extmgm.php  in line 43. Requested URL:  https://uferwerk.org/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=6efba724ddcec0056b25a5c09d5a657698582502&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bextension%5D%5Bkey%5D=piwikintegration&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=showConfigurationForm&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=Configuration
-- | --

---

**Comment by vasyugan** [comment]
Here is what the log says


  | Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class  'tx_piwikintegration_install' not found \| Error thrown in file  /var/www/chrooted/uferwerkweb/htdocs/uferwerk.org/typo3temp/ExtensionManager/UpdateScripts/ext_update4202a2abea4e1159cdd1e4c129d3ab4a.php  in line 64. Requested URL:  https://uferwerk.org/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=6efba724ddcec0056b25a5c09d5a657698582502&tx_extensionmanager_tools_extensionmanagerextensionmanager%5BextensionKey%5D=piwikintegration&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=show&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=UpdateScript
-- | --

**Comment by kaystrobach** [comment]
which version are you using? Latest master? or the version from TER?

**Comment by vasyugan** [comment]
Version 4.4.0 from TER

**Comment by kaystrobach** [comment]
Please checkout the github master, TER is always behind the master ... 😉

**Comment by vasyugan** [comment]
Indeed, the Git master works. Thanks. 

I have to admit, that now that I see it functioning, I understand that it does not do what I expected. We already have a separate Piwik install on our server and there seems to be no way to connect this extension to it. I understand that this is on your to-do list, right?

**Comment by kaystrobach** [comment]
# current state

jepp the initial strategic idea of the package was to have piwik directly and tightly integrated with TYPO3.

# plan for the future

Due to massive and ongoing API changes in the piwik code base only the API is stable, so the current idea is to just use the API to manage the piwik installation.

So the idea is to display basic information directly in TYPO3 (as we have it now), but with the restriction, that only the API is used. This would also mean, that we may need another dashboard implementation on the long term or and kind of sophisticated SSO to piwik, which is currently implemented by a custom auth plugin

# piwik source configuration

please also checkout:  https://github.com/kaystrobach/TYPO3.piwik
This one makes it easy to integrate the tracking code with various options and dynamic parts into TYPO3.

**Comment by kaystrobach** [comment]
I will close the issue for now and consider a rerelease to TER
