### ISSUE TITLE
Problems with TYPO3 8.7.10

### ISSUE THREAD

**Issue by anderlk** [kaystrobach/TYPO3.piwikintegration#93]
Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessage::render() in Extension manager

#1476107295: PHP Runtime Deprecation Notice: Non-static method TYPO3\CMS\Core\Messaging\FlashMessageQueue::addMessage() should not be called statically in Backend module

**Comment by Chrissitopher** [comment]
Fixed with #99?
